name: Verify Linked Issue In PRs

on:
  pull_request_target:
    types: [edited, synchronize, opened, reopened]
  check_run:

permissions:
  contents: read

jobs:
  conflicts:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v2
        with:
          conflict_label_name: 'need revision'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          detect_merge_changes: false
          conflict_comment: |
            :wave: Hi, @${author},
            This PR has conflicts, please resolve those before we can evaluate it.!
  verify_linked_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'Thanks a lot for your contribution! But, PR does not seem to be linked to any issues. Please [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.'
  labeler:
    if: ${{ failure() }}
    needs: [verify_linked_issue]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add Label
        uses: andymckay/labeler@1.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-labels: 'need revision'
          remove-labels: 'pending-review'
