name: Verify Linked Issue In PRs

on:
  pull_request_target:
    types: [edited, synchronize, opened, reopened]
  check_run:

permissions:
  contents: read

jobs:
  conflicts:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check Conflicts
        uses: mschilde/auto-label-merge-conflicts@master
        with:
          conflict_label_name: 'need revision'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Conflicts Comment
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            :wave: Hi @${{ github.event.issue.user.login }},
            Thanks a lot for your contribution! But, PR has conflicts, please resolve those before we can evaluate this PR.!
  verify_linked_issue:
    if: ${{ success() }}
    needs: [conflicts]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            :wave: Hi @${{ github.event.issue.user.login }},
            Thanks a lot for your contribution! But, PR does not seem to be linked to any issues. Please [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
  labeler:
    if: ${{ failure() }}
    needs: [verify_linked_issue, conflicts]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add Label
        uses: andymckay/labeler@1.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          add-labels: 'need revision'
          remove-labels: 'pending-review'
